config/routes.rb
Rails.application.routes.draw do

  resources :receipts
  resources :cart_items
  resources :carts
  root 'sessions#new'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  get 'login' => 'sessions#new'
  get 'show' => 'sessions#show'
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  post 'boards/show'

  get 'boards/pinterest_board_create'
  post 'boards/clone_board'

  post 'cart_items/add_entire_board'
  post 'cart_items/add_to_cart'
  post 'searches/index'
  get 'designs/index'
  get 'designs/show'
  get 'searches/search'
  post 'charges/index'
  post 'charges/new'

  resources :designs
  resources :users
  resources :boards
  resources :sessions
  resources :searches
  resources :charges

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :designs
  validates :user_id, presence: true
  scope :write_public, -> { where(session[:user_id] = user.id)}

  def get_first_image
    target_design = self.designs.first
    if target_design == nil
      return "http://www.iconarchive.com/download/i88574/icons8/ios7/Messaging-Sad.ico"
    else
      target_image = target_design.get_json_for_design(target_design.spoonflower_id, target_design.id)[2]
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :set_fabric_type, only: [:show]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.where(user_id: session[:user_id])
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @boards = Board.where(user_id: session[:user_id])
    if @board.marked_private == true && @board.user_id != session[:user_id]
      redirect_to boards_path, notice: "You must be the Owner of this board to view"

    elsif @board.marked_private == true && @board.user_id == session[:used_id]

    elsif @board.marked_private == false && @board.user_id != session[:used_id]

    elsif @board.marked_private == false && @board.user_id == session[:used_id]

    else
    end

    @designs = @board.designs
    @feature_display = []
    @designs.each do |design|
      @feature_display <<  design.get_json_for_design(design.spoonflower_id, design.id)
    end
  end

  # GET /boards/new
  def new
    @board = Board.new
    if session[:user_id] == nil
      redirect_to root_path, notice: "Please log in to create a board."
    end
  end

  # GET /boards/1/edit
  def edit
  end

  def clone_board
    @board = Board.find(params[:board_id])
    created_board = Board.create!(
    name: @board.name,
    user_id: session[:user_id],
    fabric_type: @board.fabric_type,
    marked_private: @board.marked_private)

    @board.designs.all.each do |design|
    created_design = Design.create!(
    board_id: created_board.id,
    spoonflower_id: design.spoonflower_id)
    end

    redirect_to boards_path
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'User was successfully created.' }
        format.js   {}
        format.json { render json: @board, notice: 'User was successfully created.'}
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fabric_type
      @fabric_type_options = [['Basic Cotton Ultra', 30], ['Satin', 40], ['Kona® Cotton', 44],
      ['Performance Piqué', 33], ['Cotton Poplin', 59], ['Poly Crepe de Chine', 39],
      ['Cotton Lawn Ultra', 47], ['Silky Faille', 23], ['Performance Knit', 21], ['Modern Jersey', 31],
      ['Cotton Spandex Jersey', 55], ['Fleece', 56], ['Minky', 46],
      ['Linen-Cotton Canvas', 52], ['Organic Cotton Knit', 5], ['Organic Cotton Sateen', 36],
      ['Sport Lycra', 50], ['Heavy Cotton Twill', 7], ['Eco Canvas', 34],
      ['Faux Suede', 32], ['Silk Crepe de Chine', 10]]
    end

    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :user_id, :marked_private, :fabric_type)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
  <%= form_for(@board) do |f| %>
    <% if @board.errors.any? %>
        <div>Please log in first to create a board.</div>
    <% end %>

    <div class="new-board-container">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
      <br>
      <%= f.hidden_field :user_id, value: session[:user_id] %>
      <br>
      <%= f.submit "CREATE", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", onclick: "notify('You created a board.');" %>
      <br>
      <br>
      <%= link_to boards_path, class: "new-board-back-btn"  do %><i class="fa fa-arrow-left" aria-hidden="true"></i><% end %>
    </div>
  <% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class="boards-index-container">
  <h3>My SpoonBoards</h3>
  <div class="boards-index-btn-wrapper">
    <a href="<%= new_board_path %>"><button class="boards-index-create-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">New Board</button></a>
  </div>
  <% @boards.each do |board| %>
    <div class="boards-index-card">
      <div class="boards-index-card-name">
        <%= board.name %>
      </div>
      <% if board.designs.as_json.length > 0 %>
        <div class="boards-index-card-image-wrapper">
        <img class="boards-index-card-image" src="<%= board.designs.first.get_json_for_design(board.designs.first.spoonflower_id, board.designs.first.id).third %>">
        </div>
      <% else %>
      <div class="boards-index-card-image-wrapper">
        <img class="boards-index-card-image" src="<%= asset_path('plus-on-page-icon.png')%>">
        </div>
      <% end %>
        <div class="boards-index-card-btn-container">
          <div class="boards-index-card-btn-wrapper">
            <%= link_to board do %>
              <button class="boards-index-create-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">SHOW</i></button>
            <% end %>
          </div>
          <div class="boards-index-card-btn-wrapper">
            <%= link_to board, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <button class="boards-index-card-remove-btn mdl-button mdl-js-button mdl-button--icon"><i class="fa fa-times" aria-hidden="true"></i></button>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="new-board-title-container">
  <h3>New Board</h3>
</div>
<%= render 'form' %>

app/views/boards/show.html.erb
  <br>
  <br>
  <div class="board-container" >
    <div class="board-name-wrapper">
      <div class="board-name">
      <span id="name">  <%= @board.name %> </span>
        <span class="board-function-hamburger"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </div>

        <div class="board-private-message">
          <%="( public )" if @board.marked_private == nil  %>
          <%="( private )" if @board.marked_private == true  %>
          <%="( public )" if @board.marked_private == false  %>
        </div>

      <!-- <div class="board-function-bar"> -->

        <!-- <br> -->
        <div>
            <% if @board.user_id == session[:user_id] %>
              <div class="design-board-btn-wrapper">
                <%= button_to cart_items_add_entire_board_path(:board_id => @board.id, :fabric_type => @board.fabric_type), :method => :post, class: "design-board-btn design-board-add-to-cart-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", onclick: "notify('You added an entire board to the cart.');" do %>
                  ADD TO CART
                <% end %>
              </div>
              &nbsp;
              <div class="design-board-btn-wrapper">
                <%= button_to "COPY", boards_clone_board_path(:board_id => @board.id), :method => :post, class: "design-board-btn design-board-copy-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", onclick: "notify('You created a copy of this board.');" %>
              </div>
            <% elsif session[:user_id] == nil %>
            <% elsif session[:user_id] != nil %>
              <div class="design-board-btn-wrapper">
                <%= button_to cart_items_add_entire_board_path(:board_id => @board.id, :fabric_type => @board.fabric_type), :method => :post, class: "design-board-btn design-board-add-to-cart-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", onclick: "notify('You added an entire board to the cart.');" do %>
                  <i class="fa fa-plus" aria-hidden="true"></i> CART
                <% end %>
              </div>
              <div class="design-board-btn-wrapper">
                <%= button_to "COPY", boards_clone_board_path(:board_id => @board.id), :method => :post, class: "design-board-btn design-board-copy-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect", onclick: "notify('You created a copy of this board.');" %></div>
            <% else %>
            <% end %>
          </div>

          <div>
          <% if @board.user_id == session[:user_id] %>
            <%= form_for(@board, remote: true) do |f| %>
              <% if @board.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>
                  <ul>
                  <% @board.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            </div>

            <div class="board-function-bar">

            <ul class="board-function-bar-items">
              <li class="">
                Name <%= f.text_field :name %>
              </li>
              <li class="">
                <%= f.hidden_field :user_id, value: session[:user_id] %> &nbsp; &nbsp; &nbsp; &nbsp;
              </li>
              <li class="">
                Fabric <%= f.select :fabric_type, @fabric_type_options%> &nbsp; &nbsp; &nbsp; &nbsp;
              </li>
              <li class="">
                <%= f.check_box :marked_private %> Private &nbsp; &nbsp; &nbsp; &nbsp;
              </li>
              <li class="">
                <%= button_to "", type: 'submit', method: :get, class: "board-show-update-btn mdl-button mdl-js-button mdl-button--icon", onclick: "notify('You updated a SpoonBoard.');" do %>
                  <i class="fa fa-refresh" aria-hidden="true"></i>
                <% end %>
              </li>

            <% end %>
          <% end %>
        </ul>

      </div> <!-- end of borad-function-bar -->

    </div> <!-- end of borad-function-wrapper -->


    <div class="gridster">
      <ul>

    <% @feature_display.each do |design|%>
      <li class="board-card" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
        <script async defer data-pin-hover="true" data-pin-round="true" src="//assets.pinterest.com/js/pinit.js"></script>
        <img class="design-thumbnail" src="<%= design.third %>">
        <div class="board-card-design-name-wrapper">Name: <a href = "https://spoonflower.com/fabric/<%= design.first %>", target="_blank"><span class="board-card-design-name"><%= design.second %></span></a></div>

        <div class="board-card-design-dropdown-wrapper">
          <% if session[:user_id] != nil %>
            <%= form_tag({controller: "designs", action: "create"}, remote: true) do %>
            <%= select_tag "design[board_id]", options_for_select(@boards.collect{ |u| [u.name, u.id] }) %>
            <%= button_tag("Add", type: "submit", name: "commit", class: "design-board-btn mdl-button mdl-js-button mdl-button--icon") do %>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <% end %>
            <%= hidden_field_tag "design[spoonflower_id]",design.first %>
            <% end %>
          <% end %>
        </div>

        <% if @board.user_id == session[:user_id] %>
          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          <div class="board-card-design-btn-wrapper">
            <%= button_to cart_items_add_to_cart_path(:design_id => design[3],:board_id => @board.id), :method => :post, class: "design-board-btn mdl-button mdl-button--icon" do %>
              <i class="fa fa-cart-plus" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="board-card-design-btn-wrapper">
            <%= button_to design_path(:design_id => design[3]), :method => :delete, class: "design-board-btn mdl-button mdl-js-button mdl-button--icon remove", remote: true do %>
              <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
          </div>
        <% end %>

      </li>

    <% end %>

    </ul>
  </div>  <!-- end of gridster -->

  </div>

  <script async defer src="//assets.pinterest.com/js/pinit.js"></script>
  <script>

  $(".mdl-textfield mdl-js-textfield mdl-textfield--floating-label").load(location.href + " .mdl-textfield mdl-js-textfield mdl-textfield--floating-label");
    $(bindDeleteDesign);

    // format design name string
    $(".board-card-design-name").each(function(){
      $(this).html(truncate($(this).html(), 20));
    });

    // is function bar visisble
    var boardFunctionVisible = false;
    /*
    * event hanldler for board funciton 'Hamburger' - toggle visibility
    */
    $(".board-function-hamburger").on("click", function() {
      console.log("** board hamburger click **");
      if (boardFunctionVisible) {
        $(".board-function-bar").slideUp(300);
        boardFunctionVisible = false;
      }
      else {
        $(".board-function-bar").slideDown(300);
        boardFunctionVisible = true;
      }
    });

    //  initialize drag & drop
    $(".gridster ul").gridster({
      widget_margins: [5, 5],
      widget_base_dimensions: [200, 290]
    });

  </script>
  <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

app/views/boards/update.js.erb
// alert("I hate this!");
$(".board-private-message").load(location.href + " .board-private-message");
// $(".board-name").val(<%= @board.name %>);
$("#name").load(location.href + " #name");
// $(".fabrics").load(location.href + " .fabrics
// $(".fabrics").val(<%= @board.fabric_type %>);


// $(".design-board-btn").load(location.href + " .design-board-btn");