config/routes.rb
Rails.application.routes.draw do

  resources :receipts
  resources :cart_items
  resources :carts
  root 'sessions#new'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  get 'login' => 'sessions#new'
  get 'show' => 'sessions#show'
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  post 'boards/show'

  get 'boards/pinterest_board_create'
  post 'boards/clone_board'

  post 'cart_items/add_entire_board'
  post 'cart_items/add_to_cart'
  post 'searches/index'
  get 'designs/index'
  get 'designs/show'
  get 'searches/search'
  post 'charges/index'
  post 'charges/new'

  resources :designs
  resources :users
  resources :boards
  resources :sessions
  resources :searches
  resources :charges

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  has_many :designs
  belongs_to :receipt

  def create_cart_item_from_design(design_properties, fabric_type)
    CartItem.create!(spoonflower_id: design_properties[0],
      design_name: design_properties[1],
      thumbnail_url: design_properties[2],
      design_id: design_properties[3],
      cart_id: design_properties[4],
      fabric_type: fabric_type)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  def add_to_cart
    design = Design.find(params[:design_id])
    @fabric_type = Board.find(params[:board_id]).fabric_type



    user_cart = User.find(session[:user_id]).carts.first.id
    api_response = []
    api_response << design.get_json_for_design(design.spoonflower_id, design.id)
    api_values = api_response.first
    api_values << user_cart
    cart_item = CartItem.new
    cart_item.create_cart_item_from_design(api_values, @fabric_type)
    redirect_to carts_path
  end

  def add_entire_board

    @board = Board.find(params[:board_id])
    @fabric_type = Board.find(params[:board_id]).fabric_type

    if @fabric_type == nil
    Board.find(params[:board_id]).fabric_type = 31
    @fabric_type = Board.find(params[:board_id]).fabric_type
    end

    user_cart = User.find(session[:user_id]).carts.first.id
    @board.designs.all.each do |design|
      api_response = []
      api_response << design.get_json_for_design(design.spoonflower_id, design.id)
      api_values = api_response.first
      api_values << user_cart
      cart_item = CartItem.new
      cart_item.create_cart_item_from_design(api_values, @fabric_type)
    end
    redirect_to carts_path
  end




  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.js   {}
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to carts_path, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:cart_id, :price, :quantity, :design_name, :design_id, :spoonflower_id, :thumbnail_url, :fabric_type, :purchased)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :design_name %><br>
    <%= f.text_field :design_name %>
  </div>
  <div class="field">
    <%= f.label :design_id %><br>
    <%= f.number_field :design_id %>
  </div>
  <div class="field">
    <%= f.label :spoonflower_id %><br>
    <%= f.number_field :spoonflower_id %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_url %><br>
    <%= f.text_field :thumbnail_url %>
  </div>
  <div class="field">
    <%= f.label :fabric_type %><br>
    <%= f.text_field :fabric_type %>
  </div>
  <div class="field">
    <%= f.label :purchased %><br>
    <%= f.check_box :purchased %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Design name</th>
      <th>Design</th>
      <th>Spoonflower</th>
      <th>Thumbnail url</th>
      <th>Fabric type</th>
      <th>Purchased</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.cart_id %></td>
        <td><%= cart_item.price %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= cart_item.design_name %></td>
        <td><%= cart_item.design_id %></td>
        <td><%= cart_item.spoonflower_id %></td>
        <td><%= cart_item.thumbnail_url %></td>
        <td><%= cart_item.fabric_type %></td>
        <td><%= cart_item.purchased %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart_item.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<p>
  <strong>Design name:</strong>
  <%= @cart_item.design_name %>
</p>

<p>
  <strong>Design:</strong>
  <%= @cart_item.design_id %>
</p>

<p>
  <strong>Spoonflower:</strong>
  <%= @cart_item.spoonflower_id %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @cart_item.thumbnail_url %>
</p>

<p>
  <strong>Fabric type:</strong>
  <%= @cart_item.fabric_type %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= @cart_item.purchased %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', carts_path %>

app/views/cart_items/update.js.erb
$(".money-stuff").load(location.href + " .money-stuff");