config/routes.rb
Rails.application.routes.draw do

  resources :receipts
  resources :cart_items
  resources :carts
  root 'sessions#new'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  get 'login' => 'sessions#new'
  get 'show' => 'sessions#show'
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  post 'boards/show'

  get 'boards/pinterest_board_create'
  post 'boards/clone_board'

  post 'cart_items/add_entire_board'
  post 'cart_items/add_to_cart'
  post 'searches/index'
  get 'designs/index'
  get 'designs/show'
  get 'searches/search'
  post 'charges/index'
  post 'charges/new'

  resources :designs
  resources :users
  resources :boards
  resources :sessions
  resources :searches
  resources :charges

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :cart
  has_many :cart_items
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:cart_item_id, :city, :adr_1, :adr_2, :state, :zip, :name, :price)
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_item_id %><br>
    <%= f.number_field :cart_item_id %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :adr_1 %><br>
    <%= f.text_field :adr_1 %>
  </div>
  <div class="field">
    <%= f.label :adr_2 %><br>
    <%= f.text_field :adr_2 %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Cart item</th>
      <th>City</th>
      <th>Adr 1</th>
      <th>Adr 2</th>
      <th>State</th>
      <th>Zip</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.cart_item_id %></td>
        <td><%= receipt.city %></td>
        <td><%= receipt.adr_1 %></td>
        <td><%= receipt.adr_2 %></td>
        <td><%= receipt.state %></td>
        <td><%= receipt.zip %></td>
        <td><%= receipt.name %></td>
        <td><%= receipt.price %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart item:</strong>
  <%= @receipt.cart_item_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @receipt.city %>
</p>

<p>
  <strong>Adr 1:</strong>
  <%= @receipt.adr_1 %>
</p>

<p>
  <strong>Adr 2:</strong>
  <%= @receipt.adr_2 %>
</p>

<p>
  <strong>State:</strong>
  <%= @receipt.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @receipt.zip %>
</p>

<p>
  <strong>Name:</strong>
  <%= @receipt.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @receipt.price %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>