config/routes.rb
Rails.application.routes.draw do

  resources :receipts
  resources :cart_items
  resources :carts
  root 'sessions#new'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#new'
  get 'login' => 'sessions#new'
  get 'show' => 'sessions#show'
  post 'create' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  post 'boards/show'

  get 'boards/pinterest_board_create'
  post 'boards/clone_board'

  post 'cart_items/add_entire_board'
  post 'cart_items/add_to_cart'
  post 'searches/index'
  get 'designs/index'
  get 'designs/show'
  get 'searches/search'
  post 'charges/index'
  post 'charges/new'

  resources :designs
  resources :users
  resources :boards
  resources :sessions
  resources :searches
  resources :charges

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpoonBoards</title>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application',"data-turbolinks-track" => true %>

    <!-- <% if params[:action] == "new" && params[:controller] == "sessions" %>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application',"data-turbolinks-track" => true %>
    boners
    <% else %>
    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => false %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
    <% end %> -->
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.grey-teal.min.css"/>
    <!-- test fonts -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300,400italic,700italic' rel='stylesheet' type='text/css'> -->
    <!-- <link rel="stylesheet" href="https://www.google.com/fonts#UsePlace:use/Collection:Montserrat:400,700" rel="stylesheet" type="text/css"> -->
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="<%= asset_path('jquery.gridster.min.css') %>" rel="stylesheet" type="text/css">
    <script src="<%= asset_path('jquery.gridster.min.js') %>"></script>
  </head>
 <% if params[:action] == "new" && params[:controller] == "sessions" %>
    <body>
  <% else %>
    <body data-no-turbolink>
  <% end %>
    <header>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/users/new" id="nav-link-sign-up">Sign Up</a></li>
          <li><%= link_to 'My SpoonBoards', boards_path, id: 'nav-link-myspoonbaords' %></li>
          <li><%= link_to 'Profile', users_path, id: 'nav-link-users'  %></li>
          <li><%= link_to 'Logout', logout_path, id: 'nav-link-logout'  %></li>
          <li id="nav-cart"><a href="/carts" id="nav-link-cart"><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i></a></li>
        </ul>
      </div>
      <div class="header-images-wrapper">
        <div class="header-title"><img class="header-title-logo" src="<%= asset_path('SPBS.png') %>" alt="Logo"></div>
        <div class="header-tag-line">Curate your Spoonflower experience</div>
      </div>
      <div class="header-search-container">
        <%= form_tag searches_path, :method => 'get' do %>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <%= text_field_tag :term, params[:term], class: "mdl-textfield__input" %>
            <label class="mdl-textfield__label" for="term">Spoonflower Marketplace Search</label>
          </div>
          <div class="header-search-btn-wrapper"><%= button_to "", :name => nil, class: "mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" do %>
            <i class="material-icons">search</i>
          <% end %>
          </div>
        <% end %>
      </div>
      <div class="notice-wrapper"><span id="notice"><%= notice %> </span></div> &nbsp;
    </header>
    <input type="hidden" name="controller_name" id="controller-name" value="<%= params[:controller] %>">
    <input type="hidden" name="controller_action" id="controller-action" value="<%= params[:action] %>">
    <input type="hidden" name="user_id" id="user-id" value="<%= session[:user_id] %>">

    <div class="yield-container">
      <%= yield %>
    </div>

    <footer class="mdl-mini-footer">
      <div class="mdl-mini-footer__left-section">
        <div class="mdl-logo">
          SpoonBoards
        </div>
        <ul class="mdl-mini-footer__link-list">
          <li><a href="https://support.spoonflower.com/hc/en-us" target="_blank">Help</a></li>
          <li><a href="http://www.spoonflower.com/terms" target="_blank" >Privacy and Terms</a></li>
          <li><a href="http://www.spoonflower.com/about" target="_blank">About Us</a></li>
        </ul>
      </div>
      <div class="mdl-mini-footer__right-section">
        <img class="footer-logo" src="<%= asset_path('spoonflower_powered_by_logo_vector_transparent.png') %>">
      </div>
    </footer>
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoonboards</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.grey-teal.min.css"/>
    <!-- test fonts -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300,400italic,700italic' rel='stylesheet' type='text/css'> -->
    <!-- <link rel="stylesheet" href="https://www.google.com/fonts#UsePlace:use/Collection:Montserrat:400,700" rel="stylesheet" type="text/css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="<%= asset_path('jquery.gridster.min.css') %>" rel="stylesheet" type="text/css">
    <script src="<%= asset_path('jquery.gridster.min.js') %>"></script>
    <!-- <script src="https://code.getmdl.io/1.1.3/material.min.js"></script> -->
  </head>
  <body>
    <header>
      
      <div class="header-images-wrapper">
        <!-- <img class="header-images" src="<%= asset_path('rdino_jade_full_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rkatta2_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rr4850076_rSPOONS1repeated_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrfitness_300_WATER_BOTTLES_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrjellyfishes_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrrcolorful_ellie_copy_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrrNOV-KID-tiger-camping-203-01_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrrrrrcosy_snuggles_revamp_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrrrVenus_Shirt_pattern_cool_tone_shades_150_18H_shop_crop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrvalentine_red_pink_brown_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rmodbabysm-dropsmint_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrturtle_single_repeat_v_final_blues-01_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('Space_Invaders_1_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrmonkey-forest2_shop_thumb.png') %>" alt="Design">
        <img class="header-images" src="<%= asset_path('rrtumblr_lx3o12NY0N1r94cc5o1_500_shop_thumb.png') %>" alt="Design"> -->
      <!-- </div> -->
      <!-- <div class="header-images-overlay"> -->
        <!-- <div class="header-title">SpoonBoards</div> -->
        <div class="header-title"><img class="header-title-logo" src="<%= asset_path('spoonboards-logo-for-header.png') %>" alt="Logo"></div>
        <div class="header-tag-line">Curate your Spoonflower experience</div>
      </div>

      <div class="notice-wrapper"><span id="notice"><%= notice %> </span></div> &nbsp;

    </header>
    <input type="hidden" name="controller_name" id="controller-name" value="<%= params[:controller] %>">
    <input type="hidden" name="controller_action" id="controller-action" value="<%= params[:action] %>">
    <input type="hidden" name="user_id" id="user-id" value="<%= session[:user_id] %>">

    <div class="yield-container">
      <%= yield %>
    </div>

<!-- === original-footer ======================================================= -->

    <!-- <footer>
      <div class="footer-container">
        <img class="footer-logo" src="<%= asset_path('spoonflower_powered_by_logo_vector_transparent.png') %>">
      </div>
    </footer> -->

<!-- === mega-footer ======================================================= -->

<!-- <footer class="mdl-mega-footer">
  <div class="mdl-mega-footer__top-section">
    <div class="mdl-mega-footer__left-section">
      <button class="mdl-mega-footer__social-btn">A</button>
      <button class="mdl-mega-footer__social-btn">B</button>
      <button class="mdl-mega-footer__social-btn">C</button>
    </div>
    <div class="mdl-mega-footer__right-section">
      <a href="#">Introduction</a>
      <a href="#">App Status Dashboard</a>
      <a href="#">Terms of Service</a>
    </div>
  </div>
  <div class="mdl-mega-footer__middle-section">
    <div class="mdl-mega-footer__drop-down-section">
      <h1 class="mdl-mega-footer__heading">Learning and Support</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Resource Center</a></li>
        <li><a href="#">Help Center</a></li>
        <li><a href="#">Community</a></li>
        <li><a href="#">Learn with Google</a></li>
        <li><a href="#">Small Business Community</a></li>
        <li><a href="#">Think Insights</a></li>
      </ul>
    </div>
    <div class="mdl-mega-footer__drop-down-section">
      <h1 class="mdl-mega-footer__heading">Just for Developers</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Google Developers</a></li>
        <li><a href="#">AdWords API</a></li>
        <li><a href="#">AdWords Scipts</a></li>
        <li><a href="#">AdWords Remarketing Tag</a></li>
      </ul>
    </div>
  </div>
  <div class="mdl-mega-footer__bottom-section">
    <div class="mdl-logo">
      More Information
    </div>
    <ul class="mdl-mega-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy and Terms</a></li>
    </ul>
  </div>
</footer> -->

<!-- === mini-footer ======================================================= -->

<!-- <footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">Title</div>
    <ul class="mdl-mini-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>
</footer> -->

<!-- ============================================================================= -->

<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">
      SpoonBoards
    </div>
    <ul class="mdl-mini-footer__link-list">
      <li><a href="https://support.spoonflower.com/hc/en-us" target="_blank">Help</a></li>
      <li><a href="http://www.spoonflower.com/terms" target="_blank" >Privacy and Terms</a></li>
      <li><a href="http://www.spoonflower.com/about" target="_blank">About Us</a></li>
    </ul>
  </div>
  <div class="mdl-mini-footer__right-section">
    <img class="footer-logo" src="<%= asset_path('spoonflower_powered_by_logo_vector_transparent.png') %>">
  </div>
</footer>

<!-- ============================================================================= -->

    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

  </body>
</html>